"""Re-analysis of the dedup threshold experiment, reusing the 32 real
questions + 20 verified paraphrases already generated by
tune_dedup_threshold.py (no new API calls — pure re-analysis).

Fix: the first pass's "distinct pairs" pool falsely included several
pairs that were actually incidental near-duplicates — the LLM generated
IDENTICAL or near-identical fill-in-blank text across different requested
difficulties, because some facts only support one natural phrasing
("The branch of Mathematics that studies patterns in whole numbers is
called ____." came out verbatim 4 times). That's real and worth noting,
but it contaminates the "known distinct" ground truth. This filters those
out via TEXT similarity (word overlap, not embedding — avoids circularity)
before computing the embedding-similarity stats.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import numpy as np
from sentence_transformers import SentenceTransformer

# --- the 32 originals, transcribed from the first run's output ---
ORIGINALS = [
    ("CHEMICAL EQUATIONS", "MCQ", "What are the substances that undergo chemical change in the reaction of magnesium with oxygen?"),
    ("CHEMICAL EQUATIONS", "MCQ", "What is formed during the reaction between magnesium and oxygen?"),
    ("CHEMICAL EQUATIONS", "MCQ", "In the reaction where magnesium ribbon is burnt in oxygen, what is the correct word-equation?"),
    ("CHEMICAL EQUATIONS", "MCQ", "What is the word-equation for the reaction between magnesium and oxygen?"),
    ("CHEMICAL EQUATIONS", "fill_in_blank", "The new substance formed during the reaction is called ____."),
    ("CHEMICAL EQUATIONS", "fill_in_blank", "The new substance formed during the reaction is ____."),
    ("CHEMICAL EQUATIONS", "fill_in_blank", "The new substance formed during the reaction is ____."),
    ("CHEMICAL EQUATIONS", "fill_in_blank", "The new substance formed during the reaction is ____."),
    ("TYPES OF CHEMICAL REACTIONS", "MCQ", "What happens to the atoms of one element during a chemical reaction?"),
    ("TYPES OF CHEMICAL REACTIONS", "MCQ", "What is true about atoms during a chemical reaction according to the textbook content?"),
    ("TYPES OF CHEMICAL REACTIONS", "MCQ", "What remains unchanged in a chemical reaction according to the content provided?"),
    ("TYPES OF CHEMICAL REACTIONS", "MCQ", "What is the main principle regarding atoms during a chemical reaction as explained in Class IX?"),
    ("TYPES OF CHEMICAL REACTIONS", "fill_in_blank", "During a chemical reaction, atoms of one element do not change into those of another ____."),
    ("TYPES OF CHEMICAL REACTIONS", "fill_in_blank", "During a chemical reaction, atoms of one element do not change into those of another ____."),
    ("TYPES OF CHEMICAL REACTIONS", "fill_in_blank", "During a chemical reaction, atoms do not disappear or appear from elsewhere; instead, chemical reactions e ____."),
    ("TYPES OF CHEMICAL REACTIONS", "fill_in_blank", "During a chemical reaction, atoms of one element do not change into those of another ____."),
    ("HAVE YOU OBSERVED THE EFFECTS", "MCQ", "What is the reddish brown powder that forms on iron when it rusts?"),
    ("HAVE YOU OBSERVED THE EFFECTS", "MCQ", "What is the reddish brown powder that forms on iron articles due to corrosion called?"),
    ("HAVE YOU OBSERVED THE EFFECTS", "MCQ", "Which of the following statements accurately describes corrosion as mentioned in the textbook?"),
    ("HAVE YOU OBSERVED THE EFFECTS", "MCQ", "What is the process called when a metal is attacked by substances around it, resulting in corrosion?"),
    ("HAVE YOU OBSERVED THE EFFECTS", "fill_in_blank", "The process commonly known as rusting of iron is a type of ____."),
    ("HAVE YOU OBSERVED THE EFFECTS", "fill_in_blank", "The process where metals are attacked by surrounding substances such as moisture is called ____."),
    ("HAVE YOU OBSERVED THE EFFECTS", "fill_in_blank", "The reddish brown powder formed on iron articles is a result of the process known as ____."),
    ("HAVE YOU OBSERVED THE EFFECTS", "fill_in_blank", "The process of iron getting coated with a reddish brown powder is commonly known as ____."),
    ("Patterns in Numbers", "MCQ", "What is the study of patterns in whole numbers called?"),
    ("Patterns in Numbers", "MCQ", "What is the name of the branch of Mathematics that studies patterns in whole numbers?"),
    ("Patterns in Numbers", "MCQ", "Which of the following sequences is classified as a number sequence studied in number theory?"),
    ("Patterns in Numbers", "MCQ", "Which of the following number sequences is known for consisting of only odd numbers?"),
    ("Patterns in Numbers", "fill_in_blank", "The branch of Mathematics that studies patterns in whole numbers is called ____."),
    ("Patterns in Numbers", "fill_in_blank", "The branch of Mathematics that studies patterns in whole numbers is called ____."),
    ("Patterns in Numbers", "fill_in_blank", "The branch of Mathematics that studies patterns in whole numbers is called ____."),
    ("Patterns in Numbers", "fill_in_blank", "The branch of Mathematics that studies patterns in whole numbers is called ____."),
]

# --- the 20 verified near-duplicate (paraphrase) pairs, transcribed from the first run ---
NEAR_DUP_PAIRS = [
    ("TYPES OF CHEMICAL REACTIONS", "What remains unchanged in a chemical reaction according to the content provided?", "What stays the same during a chemical reaction based on the given information?"),
    ("HAVE YOU OBSERVED THE EFFECTS", "What is the process called when a metal is attacked by substances around it, resulting in corrosion?", "What do we call the phenomenon where a metal is corroded by its surrounding substances, leading to corrosion?"),
    ("TYPES OF CHEMICAL REACTIONS", "During a chemical reaction, atoms do not disappear or appear from elsewhere; instead, chemical reactions e ____.", "In a chemical reaction, atoms are neither created nor destroyed; rather, these reactions e ____."),
    ("CHEMICAL EQUATIONS", "The new substance formed during the reaction is ____.", "What is the new substance that is produced as a result of the reaction?"),
    ("CHEMICAL EQUATIONS", "The new substance formed during the reaction is ____.", "What is the new substance produced in the reaction?"),
    ("CHEMICAL EQUATIONS", "What is formed during the reaction between magnesium and oxygen?", "What product is created when magnesium reacts with oxygen?"),
    ("CHEMICAL EQUATIONS", "The new substance formed during the reaction is ____.", "What is the new substance that is created during the reaction?"),
    ("TYPES OF CHEMICAL REACTIONS", "What is true about atoms during a chemical reaction according to the textbook content?", "According to the textbook content, what occurs with atoms during a chemical reaction?"),
    ("TYPES OF CHEMICAL REACTIONS", "What is the main principle regarding atoms during a chemical reaction as explained in Class IX?", "What is the key concept about atoms in a chemical reaction as discussed in Class IX?"),
    ("HAVE YOU OBSERVED THE EFFECTS", "What is the reddish brown powder that forms on iron when it rusts?", "What is the name of the reddish-brown substance that appears on iron as it rusts?"),
    ("TYPES OF CHEMICAL REACTIONS", "What happens to the atoms of one element during a chemical reaction?", "What occurs to the atoms of a single element when a chemical reaction takes place?"),
    ("CHEMICAL EQUATIONS", "The new substance formed during the reaction is called ____.", "What is the name of the new substance created during the reaction?"),
    ("CHEMICAL EQUATIONS", "What is the word-equation for the reaction between magnesium and oxygen?", "How can the reaction between magnesium and oxygen be expressed in a word equation?"),
    ("TYPES OF CHEMICAL REACTIONS", "During a chemical reaction, atoms of one element do not change into those of another ____.", "During a chemical reaction, atoms of one element do not transform into atoms of another ____."),
    ("TYPES OF CHEMICAL REACTIONS", "During a chemical reaction, atoms of one element do not change into those of another ____.", "During a chemical reaction, atoms of one element do not transform into those of another ____."),
    ("TYPES OF CHEMICAL REACTIONS", "During a chemical reaction, atoms of one element do not change into those of another ____.", "During a chemical reaction, the atoms of one element do not transform into those of a different ____."),
    ("CHEMICAL EQUATIONS", "In the reaction where magnesium ribbon is burnt in oxygen, what is the correct word-equation?", "What is the appropriate word-equation for the chemical reaction that occurs when magnesium is burnt in oxygen?"),
    ("HAVE YOU OBSERVED THE EFFECTS", "What is the reddish brown powder that forms on iron articles due to corrosion called?", "What is the name of the reddish-brown powder that develops on iron objects as a result of corrosion?"),
    ("HAVE YOU OBSERVED THE EFFECTS", "Which of the following statements accurately describes corrosion as mentioned in the textbook?", "Which of the statements below correctly characterizes corrosion as discussed in the textbook?"),
    ("CHEMICAL EQUATIONS", "What are the substances that undergo chemical change in the reaction of magnesium with oxygen?", "Which substances are involved in the chemical change during the reaction between magnesium and oxygen?"),
]


def word_overlap_ratio(a: str, b: str) -> float:
    """Cheap text-level (not embedding) similarity for filtering
    incidental generation duplicates out of the 'known distinct' ground
    truth -- avoids circularity with the embedding metric being tuned."""
    wa, wb = set(a.lower().split()), set(b.lower().split())
    if not wa or not wb:
        return 0.0
    return len(wa & wb) / len(wa | wb)


def cosine_sim(a, b) -> float:
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    embed_model = SentenceTransformer("all-MiniLM-L6-v2")

    # near-dup similarities (unchanged from the first pass -- these are genuine, verified paraphrases)
    near_dup_sims = []
    for topic, a, b in NEAR_DUP_PAIRS:
        ea, eb = embed_model.encode([a, b])
        near_dup_sims.append(cosine_sim(ea, eb))

    # distinct pairs: all combinations of DIFFERENT originals, but now
    # filtered by word-overlap to exclude incidental generation duplicates
    CONTAMINATION_THRESHOLD = 0.6  # word-overlap ratio above which we don't trust the "distinct" label
    kept, excluded = [], []
    for i in range(len(ORIGINALS)):
        for j in range(i + 1, len(ORIGINALS)):
            _, _, a = ORIGINALS[i]
            _, _, b = ORIGINALS[j]
            if a == b:
                excluded.append((a, b, 1.0))
                continue
            overlap = word_overlap_ratio(a, b)
            if overlap >= CONTAMINATION_THRESHOLD:
                excluded.append((a, b, overlap))
            else:
                kept.append((ORIGINALS[i][0] == ORIGINALS[j][0], a, b))

    print(f"Excluded {len(excluded)} contaminated pairs (incidental near-duplicate generations), kept {len(kept)} genuinely-distinct pairs\n")
    print("Excluded pairs (for transparency):")
    for a, b, overlap in excluded:
        print(f"  word_overlap={overlap:.2f}  A={a[:60]!r}  B={b[:60]!r}")

    distinct_sims_same_topic, distinct_sims_diff_topic = [], []
    for same_topic, a, b in kept:
        ea, eb = embed_model.encode([a, b])
        sim = cosine_sim(ea, eb)
        (distinct_sims_same_topic if same_topic else distinct_sims_diff_topic).append(sim)

    def stats(name, values):
        arr = np.array(values)
        print(f"{name}: n={len(arr)}  min={arr.min():.3f}  p25={np.percentile(arr,25):.3f}  "
              f"median={np.median(arr):.3f}  p75={np.percentile(arr,75):.3f}  p95={np.percentile(arr,95):.3f}  max={arr.max():.3f}")

    print("\n=== CORRECTED cosine SIMILARITY distributions ===")
    stats("Near-duplicate pairs (verified paraphrases)      ", near_dup_sims)
    stats("Genuinely-distinct pairs, SAME topic (hard case)  ", distinct_sims_same_topic)
    stats("Genuinely-distinct pairs, DIFFERENT topic (easy)  ", distinct_sims_diff_topic)

    all_distinct = distinct_sims_same_topic + distinct_sims_diff_topic
    near_sorted = sorted(near_dup_sims)
    distinct_sorted = sorted(all_distinct, reverse=True)

    print(f"\nNear-dup similarities, lowest 5:  {[round(s,3) for s in near_sorted[:5]]}")
    print(f"Distinct-pair similarities, highest 5: {[round(s,3) for s in distinct_sorted[:5]]}")

    # find the threshold that best separates: minimize (false merges + missed dups)
    # by scanning candidate thresholds
    candidates = sorted(set(round(s, 3) for s in near_dup_sims + all_distinct))
    best = None
    for t in candidates:
        missed_dups = sum(1 for s in near_dup_sims if s < t)
        false_merges = sum(1 for s in all_distinct if s >= t)
        total_errors = missed_dups + false_merges
        if best is None or total_errors < best[0]:
            best = (total_errors, t, missed_dups, false_merges)

    print(f"\nBest-separating threshold by error count: similarity >= {best[1]:.3f} "
          f"({best[2]} near-dups missed, {best[3]} distinct pairs false-merged, {best[0]} total errors)")

    # conservative recommendation: bias toward fewer false merges (PLAN.md
    # section 5: "start conservative") -- report a couple of candidates
    for bias_t in [best[1], 0.90, 0.92]:
        missed = sum(1 for s in near_dup_sims if s < bias_t)
        merged = sum(1 for s in all_distinct if s >= bias_t)
        print(f"  threshold={bias_t:.3f}: catches {len(near_dup_sims)-missed}/{len(near_dup_sims)} near-dups, "
              f"false-merges {merged}/{len(all_distinct)} distinct pairs")


if __name__ == "__main__":
    main()
